import os
import json
import csv
import platform
import subprocess

from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib.pagesizes import letter

from reportlab.pdfgen import canvas

from reportlab.lib.colors import grey

from rich import print
from rich.console import Console
from rich.table import Table


console = Console()


def open_report_file(file_path):

    try:

        system = platform.system()

        if system == "Windows":

            os.startfile(file_path)

        elif system == "Darwin":

            subprocess.run([
                "open",
                file_path
            ])

        else:

            subprocess.run([
                "xdg-open",
                file_path
            ])

    except Exception as e:

        print(
            f"[red]"
            f"Failed to open report:"
            f"[/red] {e}"
        )


def add_watermark(
    canvas_obj,
    doc
):

    canvas_obj.saveState()

    # Watermark
    canvas_obj.setFont(
        "Helvetica",
        40
    )

    canvas_obj.setFillColor(
        grey,
        alpha=0.15
    )

    canvas_obj.translate(
        300,
        400
    )

    canvas_obj.rotate(45)

    canvas_obj.drawCentredString(
        0,
        0,
        "Cyber Recon Toolkit"
    )

    canvas_obj.restoreState()

    # Footer
    canvas_obj.setFont(
        "Helvetica",
        8
    )

    canvas_obj.setFillColor(
        grey
    )

    canvas_obj.drawString(
        40,
        20,
        (
            "Generated by Cyber Recon Toolkit | "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        )
    )


def generate_pdf_report(
    report_data,
    output_file
):

    try:

        doc = SimpleDocTemplate(
            output_file,
            pagesize=letter
        )

        styles = getSampleStyleSheet()

        elements = []

        title = Paragraph(
            "Cyber Recon Toolkit Report",
            styles["Title"]
        )

        elements.append(title)

        elements.append(
            Spacer(1, 20)
        )

        generated = Paragraph(
            f"Generated: "
            f"{report_data['report_generated']}",
            styles["Normal"]
        )

        elements.append(generated)

        elements.append(
            Spacer(1, 20)
        )

        for module, content in (
            report_data[
                "module_reports"
            ].items()
        ):

            heading = Paragraph(
                f"<b>{module}</b>",
                styles["Heading2"]
            )

            elements.append(heading)

            pretty_json = json.dumps(
                content,
                indent=4
            ).replace(
                "\n",
                "<br/>"
            )

            paragraph = Paragraph(
                f"<font face='Courier'>"
                f"{pretty_json}"
                f"</font>",
                styles["BodyText"]
            )

            elements.append(paragraph)

            elements.append(
                Spacer(1, 15)
            )

        doc.build(
            elements,
            onFirstPage=add_watermark,
            onLaterPages=add_watermark
        )

        return True

    except Exception as e:

        print(
            f"[red]"
            f"Failed to generate PDF:"
            f"[/red] {e}"
        )

        return False


def generate_combined_report():

    report_data = {}

    timestamp = datetime.now().strftime(
        "%Y-%m-%d_%H-%M-%S"
    )

    report_data["report_generated"] = (
        timestamp
    )

    reports_folder = "reports"

    if not os.path.exists(reports_folder):

        os.makedirs(reports_folder)

    report_files = [
        f for f in os.listdir(reports_folder)
        if (
            f.endswith(".json")
            and not f.startswith(
                "combined_report"
            )
        )
    ]

    if not report_files:

        print(
            "[yellow]"
            "No module reports found "
            "in reports folder."
            "[/yellow]"
        )

        return None

    report_data["module_reports"] = {}

    print(
        "\n[bold yellow]"
        "Collecting module reports..."
        "[/bold yellow]"
    )

    for file in report_files:

        try:

            with open(
                os.path.join(
                    reports_folder,
                    file
                ),
                "r"
            ) as f:

                module_name = file.replace(
                    ".json",
                    ""
                )

                report_data[
                    "module_reports"
                ][module_name] = json.load(f)

        except Exception as e:

            print(
                f"[red]"
                f"Failed to read {file}:"
                f"[/red] {e}"
            )

    # Summary table
    table = Table(
        title="Loaded Reports Summary"
    )

    table.add_column(
        "Report File",
        style="cyan"
    )

    table.add_column(
        "Status",
        style="green"
    )

    for file in report_files:

        table.add_row(
            file,
            "Loaded"
        )

    console.print(table)

    # Save combined JSON
    combined_json_file = (
        f"{reports_folder}/"
        f"combined_report_"
        f"{timestamp}.json"
    )

    try:

        with open(
            combined_json_file,
            "w"
        ) as f:

            json.dump(
                report_data,
                f,
                indent=4
            )

        print(
            f"\n[bold green]"
            f"Combined JSON report saved:"
            f"[/bold green] "
            f"{combined_json_file}"
        )

    except Exception as e:

        print(
            f"[red]"
            f"Error saving JSON report:"
            f"[/red] {e}"
        )

    # Save combined CSV
    combined_csv_file = (
        f"{reports_folder}/"
        f"combined_report_"
        f"{timestamp}.csv"
    )

    try:

        with open(
            combined_csv_file,
            "w",
            newline=""
        ) as csvfile:

            writer = csv.writer(csvfile)

            writer.writerow([
                "Module",
                "Target",
                "Key",
                "Data"
            ])

            for module, content in (
                report_data[
                    "module_reports"
                ].items()
            ):

                if isinstance(content, dict):

                    for key, value in content.items():

                        writer.writerow([
                            module,
                            key,
                            "",
                            json.dumps(value)
                        ])

                else:

                    writer.writerow([
                        module,
                        "",
                        "",
                        json.dumps(content)
                    ])

        print(
            f"[bold green]"
            f"Combined CSV report saved:"
            f"[/bold green] "
            f"{combined_csv_file}"
        )

    except Exception as e:

        print(
            f"[red]"
            f"Error saving CSV report:"
            f"[/red] {e}"
        )

    # Save PDF report
    combined_pdf_file = (
        f"{reports_folder}/"
        f"combined_report_"
        f"{timestamp}.pdf"
    )

    pdf_created = generate_pdf_report(
        report_data,
        combined_pdf_file
    )

    if pdf_created:

        print(
            f"[bold green]"
            f"Combined PDF report saved:"
            f"[/bold green] "
            f"{combined_pdf_file}"
        )

    return (
        combined_json_file,
        combined_csv_file,
        combined_pdf_file
    )


def generate_report_menu():

    print(
        "\n[bold cyan]"
        "===== REPORT GENERATOR ====="
        "[/bold cyan]"
    )

    result = generate_combined_report()

    if not result:

        return

    (
        json_report,
        csv_report,
        pdf_report
    ) = result

    while True:

        print("\n1. Open JSON Report")
        print("2. Open CSV Report")
        print("3. Open PDF Report")
        print("4. Back to Main Menu")

        choice = console.input(
            "\n[bold green]"
            "Choice >[/bold green] "
        ).strip()

        if choice == "1":

            open_report_file(
                json_report
            )

        elif choice == "2":

            open_report_file(
                csv_report
            )

        elif choice == "3":

            open_report_file(
                pdf_report
            )

        elif choice == "4":

            break

        else:

            print(
                "[red]"
                "Invalid choice"
                "[/red]"
            )